#**NUMPY starting**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype = 'float64')
a

array([1., 2., 3.])

In [ ]:
b = np.array([[1,2,3,4.0,5],[6,8,4,4,6]])
print(b)

[[1. 2. 3. 4. 5.]
 [6. 8. 4. 4. 6.]]


In [ ]:
# get the deminsion of np array
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# get the shape of the array
print(a.shape)
print(b.shape)

(3,)
(2, 5)


In [ ]:
# get the datatype inside the array
print(a.dtype)
print(b.dtype)

float64
float64


In [ ]:
# get the size of each element in the array 
print(a.itemsize)
# the total size 
print(a.nbytes)

8
24


# **access specific data, rows, columns or whatever**

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
# get specific element [r, c]
print(a[1,4])

# you can use the -ve notation just like lists
print(a[1,-4])

10
7


In [ ]:
# get a specific row
print(a[0, :])
type(a[0, :])

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# get a specific column
print(a[:, 0])
type(a[:, 0])

[1 6]


numpy.ndarray

In [ ]:
# getting a little bit fancy [startindex: fincalindex: the_step , startindex: fincalindex: the_step]
a[0, 4:1:-1]

array([5, 4, 3])

In [ ]:
# changing sth
print(a)
a[1,2] = 20 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7 20  9 10]]


In [ ]:
# changing an entire column or row [r, c]
a[:,1] = 5
print(a)
print()
a [:,1] = [1,2]
print(a)

[[ 1  5  3  4  5]
 [ 6  5 20  9 10]]

[[ 1  1  3  4  5]
 [ 6  2 20  9 10]]


#**Initializeing Differernt Types of array**

In [ ]:
# All zeros Matrex 
np.zeros((4,2), dtype = float)


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# All ones Matrex
np.ones((4,2,1), dtype = int)

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [ ]:
# full with any stuff
np.full((2,2), 9999)

array([[9999, 9999],
       [9999, 9999]])

In [ ]:
# very noughty stuff
print(a.shape)
print()
print(np.full(a.shape, 9)) # use a.shape
print()
print(np.full_like(a, 9)) #use a

(4, 2)

[[9 9]
 [9 9]
 [9 9]
 [9 9]]

[[9. 9.]
 [9. 9.]
 [9. 9.]
 [9. 9.]]


In [ ]:
# random decimal numbers (0-1)
np.random.rand(3,2) # you pass-in the shape directly, not in a tuple form

np.random.random_sample(a.shape)

array([[1.78393213e-01, 9.82889214e-01],
       [9.96869771e-01, 3.08727089e-01],
       [6.48751948e-02, 5.94589597e-04],
       [2.01755730e-01, 3.34440705e-01]])

In [ ]:
np.random.randint(0, 5, size = (3,3)) # or 
np.random.randint(5, size = (3,3)) # starting by difault as 0 

array([[4, 0, 1],
       [4, 4, 1],
       [0, 2, 2]])

In [ ]:
# the identitiy matrex
np.identity(3) # only one parameter 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeating the array
arr = np.array([[1,2,3],[3,3,3]])
np.repeat(arr, 3, axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

Try to understand those 2 approches to the same output...

In [ ]:
a = np.zeros((5,5))
a[2,2]= 9
a[0,:] = 1
a[:,0] = 1
a[-1,:] = 1
a[:,-1] = 1
a 

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
output = np.ones((5,5))
input = np.zeros((3,3))
output[1:4,1:4] = input
output[2,2] = 9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**be carefull when copying arrays!**

In [ ]:
a = np.ones((4,4))
b = a
b[0,0] = 9

In [ ]:
print(b)

[[9. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(a) #it didnt just give b the values of a, it made b , a .... literally they are the same now, you van check the id!!

[[9. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(id(a))
print(id(b))

140462852999808
140462852999808


In [ ]:
# you can try ...
b = a.copy
print(id(b))
print(a==b)

140462854103360
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


#Math


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a += 2
a

array([5, 6, 7, 8])

In [ ]:
b = np.array([1,0,1,0])

In [ ]:
a + b

array([6, 6, 8, 8])

In [ ]:
a ** 2

array([25, 36, 49, 64])

In [ ]:
# take the 'sin' , 'cos' of all the values 
np.sin(a)
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

#**Linear Algebra**

In [ ]:
a = np.full((2,3),1)
b = np.full((3,2),2)
print(a)
print()
print(b)
# to multiply 2 matrices , their shape should look like (far5a,x),(x,bata) , then a*b = (far5a, bata)

[[1 1 1]
 [1 1 1]]

[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b) # :D

array([[6, 6],
       [6, 6]])

In [ ]:
# find the determinate of an array
a = np.identity(5)
np.linalg.det(a)

1.0

# **Statistics**

In [ ]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.min(stats)
np.min(stats, axis = 1) # axis = 1 ... column

array([1, 5])

In [ ]:
np.max(stats)
np.max(stats, axis = 0)

array([5, 6, 7, 8])

In [ ]:
np.sum(stats)

36

# **Reorganizing arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before.shape

after = before.reshape((8,1))
after # when you get an error, so the values can not fit

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
# horizontally stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# **From Google Co-lab import files**

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
file_data = np.genfromtxt('name of the stuff you wanna make as a np', delimiter= ',') # delimiter is similar to "sep" in pandas
file_data = file_data.astype('int8')

# **boolean Masking and advanced indexing**

In [ ]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [ ]:
a > 3 #Boolean Masking

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [ ]:
a[a > 3] #Grabbing all the vlueas with condetion True and put them all into an array 

array([4, 5, 4, 5, 4, 5])

In [ ]:
# YOu can index with a list in numPy :D
b = np.array([1,2,3,4,5,6,7,8,9])
b[[1,2,8]]

array([2, 3, 9])

In [ ]:
a[[1,2],:] # row number 1 and 2, but all columns

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
# do some indexing stuff 